//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoslynProofsConsole.DevfishServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/EightBallWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DevfishServices.IEightBallService")]
    public interface IEightBallService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBallService/GetData", ReplyAction="http://tempuri.org/IEightBallService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBallService/GetData", ReplyAction="http://tempuri.org/IEightBallService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBallService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IEightBallService/GetDataUsingDataContractResponse")]
        RoslynProofsConsole.DevfishServices.CompositeType GetDataUsingDataContract(RoslynProofsConsole.DevfishServices.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBallService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IEightBallService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<RoslynProofsConsole.DevfishServices.CompositeType> GetDataUsingDataContractAsync(RoslynProofsConsole.DevfishServices.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBallService/AskQuestion", ReplyAction="http://tempuri.org/IEightBallService/AskQuestionResponse")]
        string AskQuestion(string question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBallService/AskQuestion", ReplyAction="http://tempuri.org/IEightBallService/AskQuestionResponse")]
        System.Threading.Tasks.Task<string> AskQuestionAsync(string question);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEightBallServiceChannel : RoslynProofsConsole.DevfishServices.IEightBallService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EightBallServiceClient : System.ServiceModel.ClientBase<RoslynProofsConsole.DevfishServices.IEightBallService>, RoslynProofsConsole.DevfishServices.IEightBallService {
        
        public EightBallServiceClient() {
        }
        
        public EightBallServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EightBallServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EightBallServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EightBallServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public RoslynProofsConsole.DevfishServices.CompositeType GetDataUsingDataContract(RoslynProofsConsole.DevfishServices.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<RoslynProofsConsole.DevfishServices.CompositeType> GetDataUsingDataContractAsync(RoslynProofsConsole.DevfishServices.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string AskQuestion(string question) {
            return base.Channel.AskQuestion(question);
        }
        
        public System.Threading.Tasks.Task<string> AskQuestionAsync(string question) {
            return base.Channel.AskQuestionAsync(question);
        }
    }
}
